server:
  port: 7075
  servlet:
    context-path: /user


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25001/eureka/


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sigec_user_db
    username: sigec
    password: Sigec@Ceenet2020


logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.ceenet.sigec.ws: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"



