server:
  port: 7073

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25001/eureka/


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sigec_process
    username: root
    password: password



