server:
  port: 7074
  servlet:
    context-path: /payment

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25001/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sigec_payment?createDatabaseIfNotExist=true
    username: sigec
    password: Sigec@Ceenet2020

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.ceenet.sigec.ws: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"


##  SICAPAY PARAMETERS
sycapay:
  parameter:
    base-url: https://dev.sycapay.net/api
    notification-url :
    marchand-id: C_6012D4B5E9759
    apikey: pk_syca_4d4ac88674fee126ebd106583335fc4ef298d541
    request-data-format: JSON
    response-data-format: JSON



