server:
  port: 7072

logging:
    level:
      root: ERROR
      org.apache.: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25001/eureka/



spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sigec_notification
    username: sigec
    password: Sigec@Ceenet2020


ovh:
  application:
    key: TTAtEKIe8hnWC1BF
    secret: lWDBYFLDsLY7aI8SnFtkRQ4OBkXCmOH9
  consumer:
    key: XyKQZH7KnXKmxLfB8wwIQ7OVfLYXXmh2
  service:
    name: sms-as137940-1
  request:
    method: POST
    url: https://eu.api.ovh.com/1.0/sms/
    sender: 4ITAfrica
